### ISSUE TITLE
Gallery page - footer text is white

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/VCUarts-AFO-2014#66]
Should be black - right now it's not visible

**Comment by dstrogiy** [comment]
![screen shot 2015-01-13 at 3 01 20 pm](https://cloud.githubusercontent.com/assets/6132788/5728010/1ba13dae-9b35-11e4-9143-0cb613d6e9bf.png)
nav too 💂

**Comment by streeetlamp** [comment]
![sekujy8](https://cloud.githubusercontent.com/assets/1740634/5728659/daffca4a-9b39-11e4-9c3b-4213810f0b19.gif)
