### ISSUE TITLE
On FF desktop view footer info is missing

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/VCUarts-AFO-2014#68]
The <br> tags are not going inline or displaying none - not sure the setup exactly but it's working everywhere else it seems

**Comment by dstrogiy** [comment]
4987339
![tumblr_mkmg6pttgv1rz41lqo1_r1_400](https://cloud.githubusercontent.com/assets/6132788/5781998/77815c1a-9d85-11e4-9586-3c005ba31fb0.gif)
